
mongo_settings:
  db_name: "twitch_streams"
  collection_name: 'streams_irl_31.05.2022'
  primary_key: null  # Stream id


general_settings:
  output_folder: 'Assets/${mongo_settings.collection_name}'

excluded_clips:
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_15.05.2022/dumped_clips_data.json"
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_18.05.2022/dumped_clips_data.json"
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_22.05.2022/dumped_clips_data.json"
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_25.05.2022/dumped_clips_data.json"
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_29.05.2022/dumped_clips_data.json"
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_31.05.2022/dumped_clips_data.json"

included_channels:
  - h1s0yam

channels_condition:
  viewer_count: "<=40"

excluded_channels:
  # - LES_SHOW  # - Name
  - excluded_streamers.txt  # Txt file

clips_scrapper:
  game_names: ["Just Chatting"]
  max_clips_count: 30
  start: now  # In '%d/%m/%y %H:%M:%S' format on now for ex 18/09/19 01:55:19
  before_days: 15
  conditions:
    view_count: ">=10"

