
mongo_settings:
  db_name: "twitch_streams"
  collection_name: 'streams_irl_11.05.2022'
  primary_key: null  # Stream id


general_settings:
  output_folder: 'Assets/${mongo_settings.collection_name}'

excluded_clips:
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_08.05.2022/dumped_clips_data.json"
  - "/home/malchul/work/streams/stream_parser/Assets/streams_irl_05.05.2022/dumped_clips_data.json"

channels_condition:
  viewer_count: "<=35"

excluded_channels:
  - LES_SHOW

clips_scrapper:
  game_names: ["Just Chatting"]
  max_clips_count: 30
  start: now  # In '%d/%m/%y %H:%M:%S' format on now for ex 18/09/19 01:55:19
  before_days: 15
  conditions:
    view_count: ">=10"

