clips_path: '/home/malchul/work/streams/stream_parser/Assets/streams_irl_11.05.2022/editor_clips_videos.clps'
video_resolution: [ 1920, 1080 ]


screen_transition: '/home/malchul/work/streams/stream_parser/Assets/Translation/screen_translation_.mp4'